### ISSUE TITLE
xcodeproj file is missing

### ISSUE THREAD

**Issue by alouanemed** [Cordt/Lentil#1]
It seems that you removed `Lentil.xcodeproj/project.pbxproj` on this commit https://github.com/Cordt/Lentil/commit/b8469242cbb4a3adad0150c6dcd6af7fb1f544f3

**Comment by Cordt** [comment]
Thanks for pointing this out.
Will have a look at that

**Comment by Cordt** [comment]
Added the missing workspace back to the index.

To run this there is a little more work to do, but I will only write a documentation once there is a stable version that is worth checking out.

You will definitely need to set the following environment variables:
"TEST_WALLET_PRIVATE_KEY"
"TEST_WALLET_PASSWORD"
"BASE_URL"

and manually run the Apollo Build Phase.

**Comment by alouanemed** [comment]
@Cordt 
Great 🤩
Where do you those from? Also I saw that you are migrating to ReducerProtocole, I started migrating a small project as well. If you are planning to priorities this, I can provide some help.

**Comment by Cordt** [comment]
I'd recommend to use a key pair that is associated with a test account on Mumbai devnet.
I will write a documentation at some point so it's easier to setup the project, but for the moment I need to give the project more direction, before that makes sense.

The ReducerProtocol migration is already done, wasn't too bad ;)
Thanks for your support!

**Comment by alouanemed** [comment]
@Cordt 
Thanks for your response.
But, what's Mumbai devnet? It seems that other info are needed for the app:

    #if DEBUG
    self.logLevel = LogLevel(rawValue: ProcessInfo.processInfo.environment["LOG_LEVEL"]!.lowercased())!
    self.baseUrl = ProcessInfo.processInfo.environment["BASE_URL"]!
    self.origin = ProcessInfo.processInfo.environment["ORIGIN"]!
    self.testWalletAddress = ProcessInfo.processInfo.environment["TEST_WALLET_ADDRESS"]!
    #else

**Comment by Cordt** [comment]
Hey, have a look here: https://docs.lens.xyz/docs/api-links

Log level can be ERROR, WARN, DEBUG, INFO
ORIGN is the url of the app, as it will be used in the API header.

The reason these things are env variables is because they will be specific to your application, if you build one.

I will have to change that design one more time as it doesn't allow for secrets to be stored.
